CREATE TABLE [dbo].[OS] (
    [OID]    INT NOT NULL,
    [SID]    INT NOT NULL,
    [NCount] INT NULL,
    CONSTRAINT [PK_OS] PRIMARY KEY CLUSTERED ([OID] ASC, [SID] ASC),
    CONSTRAINT [FK_OS_OID] FOREIGN KEY ([OID]) REFERENCES [dbo].[Object] ([OID]),
    CONSTRAINT [FK_OS_SID] FOREIGN KEY ([SID]) REFERENCES [dbo].[Segment] ([SID])
);

