CREATE TABLE [dbo].[ST] (
    [SID]    INT NOT NULL,
    [TID]    INT NOT NULL,
    [NCount] INT NULL,
    CONSTRAINT [PK_ST] PRIMARY KEY CLUSTERED ([SID] ASC, [TID] ASC),
    CONSTRAINT [FK_ST_SID] FOREIGN KEY ([SID]) REFERENCES [dbo].[Segment] ([SID]),
    CONSTRAINT [FK_ST_TID] FOREIGN KEY ([TID]) REFERENCES [dbo].[Token] ([TID])
);

